apiVersion: v1
kind: Service
metadata:
  name: routes-api-gateway
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: routes-api-gateway
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: routes-api-gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: routes-api-gateway
    spec:
      containers:
        - name: esp
          image: gcr.io/endpoints-release/endpoints-runtime:1
          args: [
            "-P", "9000",
            "-a", "grpc://127.0.0.1:50051",
            "-s", "routes-api-gateway.endpoints.routes-services.cloud.goog",
            "--rollout_strategy", "managed",
          ]
          ports:
            - containerPort: 9000
        - name: echo
          image: gcr.io/routes-services/routes-api-gateway:latest
          ports:
            - containerPort: 50051
          env:
            - name: REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: routes-api-gateway-secret
                  key: redis_address
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routes-api-gateway-secret
                  key: redis_password